services:
  churn_api:
    build: .
    image: scorpio1317/mohamedatef-churnprediction:694
    container_name: churn_api
    ports:
      - "8005:8000" # host --> container

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - churn_api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  locust:
    image: locustio/locust
    # 1) mount your test script
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    # 2) override the command to point at that file, and tell it where the API is
    command: >
      -f /mnt/locust/locustfile.py
      --host http://churn_api:8000
    # 3) map UI port 8089 → host 8007
    ports:
      - "8007:8089"
    depends_on:
      - churn_api