version: "3.8"

services:
  churn_api:
    image: mohamedatef:latest
    container_name: churn_api
    ports:
      - "8000:8000"
    environment:
      # required by prometheus_fastapi_instrumentator
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    volumes:
      - /tmp:/tmp

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
