global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bank_churn_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['tmwcmkutwyjr.us-east-1.clawcloudrun.com:8000']    
      #- targets: ['churn_api:8000']
